[build-system]
requires = ["Cython>=0.27.1", "setuptools", "wheel"]

[tool.black]
line-length = 100
target-version = ['py37', 'py38', 'py39']

[tool.isort]
profile = "black"
line_length = 100
treat_all_comments_as_code = "True"
add_imports = ["from __future__ import annotations"]
blocked_extensions = ['pex', 'pyx', 'pxd']
supported_extensions = ["py"]
